const en_US = {
    home:"Home",
    contactUs:"Contact Us",
    userCenter:"User Center",
    logout:"Logout",
    login:"Login",
    register:"Register",
    registerNow:"Register Now",
    userCheck:"Management Center",
    ourAdvantages:"Our advantages",
    ourVision:"Our Vision",
    contactUsTitle:"Contact Us",
    disclaimer:"Disclaimer",
    basicVIP:"Basic VIP",
    advancedVIP:"Advanced VIP",
    basicCheck:"Basic Check",
    advancedCheck:"Advanced Check",
    unreviewed:"Unreviewed",
    linkman:"Linkman",
    messageCenter:"Message Center",
    basicVIPTip1:"Please fill in the ID number, the same ID number can only be bound to an account [Required]",
    basicVIPTip2:"The name must be the same as the ID [Required]",
    basicVIPTip3:"The address must be the same as the ID address [Optional]",
    basicVIPTip4:"employment status [Required]",
    checkTip1:"Job status",
    checkTip2:"Buy for others？",
    checkTip3:"front of ID card",
    checkTip4:"back of ID card",
    basicVIPTip5:"Are you purchasing or purchasing on behalf of a third party? [Required]",
    basicVIPTip6:"Upload ID photo",
    basicVIPTip7:"1. The file is a digital photo, please do not beautify or modify it to avoid the application failed",
    basicVIPTip8:"2. Upload file format support png, jpg and bmp",
    basicVIPTip9:"3 File size does not exceed 3MB, the minimum file size is 200px*150px",
    basicVIPTip10:"Click to upload ID card front",
    basicVIPTip11:"Click to upload ID card obverse",
    basicVIPTip12:"ID number",
    basicVIPTip13:"Name",
    basicVIPTip14:"Address",
    basicVIPTip15:"Image loading",
    basicVIPOption1:"working ",
    basicVIPOption2:"student",
    basicVIPOption3:"unemployment",
    basicVIPOption4:"retire",
    basicVIPOption5:"other",
    submit1:"under review",
    submit2:"submit",
    submit3:"verified",
    advancedVIPTip1:"Please fill in your passport number [Required]",
    advancedVIPTip2:"Passport expiration date [Required]",
    advancedVIPTip3:"Expected annual income [Optional]",
    advancedVIPTip4:"Net worth (excluding non-current assets such as homes and vehicles) [Optional]",
    advancedVIPTip5:"Sources of funds [Required]",
    checkTip5:"Sources of funds",
    checkTip6:"Expiration date",
    checkTip7:"Passport",
    advancedVIPTip6:"Upload ID photo",
    advancedVIPTip7:"Click to upload passport photos",
    advancedVIPTip8:"passport number",
    advancedVIPTip9:"expected annual income",
    advancedVIPTip10:" net worth",
    advancedVIPOption1:"income",
    advancedVIPOption2:"income from investment",
    advancedVIPOption3:"pension/Retirement savings",

    mesList1:"Time",
    createTime:"registration date",
    mesList2:"Content",
    userCheck1:"nickname",
    userCheck2:"account",
    userCheck3:"grade",
    userCheck4:"operation",
    loginBoxTitle:"Please log in",
    importLEmail:"Please enter your email address",
    importRLEmail:"Please enter the mailbox in the correct format!",
    importLCode:"Please enter the code",
    importRLCode:"Please enter the verification code in the correct format!",
    importLPwd:"Password 6-24 bit letters, Numbers, characters",
    importRLPwd:"Please enter the correct password!",
    importCLPwd:"Please check your password!",
    loginNow:"Login immediately",
    forget:"Forget",
    noAccount:"No account",
    yesAccount:"Existing account",
    regBoxTitle:"Please register",
    importRTPwd:"Please enter your password again.",
    importRRTPwd:"The password of two input is different!",
    regNow:"Complete and login",
    forgetBoxTitle:"Forget password",
    regComplete:"Registr Complete",
    importBoxTitle:"Please go to registered email and follow the prompts for the next step",
    regSuccess:"Register success",
    submitSuccess:"Submit success",
    resetPwd:"Reset Password",
    pwdChange:"Confirm password change",
    yes:"yes",
    no:"no",
    all:"All",
    pass:"Pass",
    passed:"Passed",
    noPass:"No pass",
    isSure:"Is confirmation approved?",
    location:"Location",
    userCheckList:"User Check",
    checkHistory:"Check History",
    userChat:"User Chat",
    sendMail:"Send Email",
    notReason:"NoPassTxt：",
    send:"send",
    selected:"Selected",
    items:"items",
    contactAdmin:"Contact Trader",
    admin:"admin",
    basicCant:"Basic VIP failed",
    RMwechat:"Relationship Manager WeChat",
    language:"English",
    disclaimer1:"Users expressly agree that their use of the company's services will be entirely at their own risk. As a result of their use of the company's services and all the consequences arising from its own, the company does not assume any responsibility to the user. ",
    disclaimer2:"Any information provided by the company (including but not limited to those provided by the company, externally, and issued by others invited by the company), the company can not guarantee that it is completely real-time or completely accurate, nor does it mean that the company confirms its describe or agree with their point of view.  ",
    disclaimer3:" All content is for reference only, does not constitute investment advice or other practical operating advice. The user is responsible for the consequences of this operation. ",
}
export default en_US;